[package]
name = "crypto_common_derive"
version = "0.1.0"
authors = ["Concordium AG <contact@concordium.com>"]
edition = "2018"

[lib]
proc-macro=true

[dependencies]
syn = { version = "1.0", features = [ "extra-traits" ] }
quote = "=1.0"
proc-macro2 = "1.0"