[package]
name = "wasm-test"
version = "0.1.0"
authors = ["Concordium <developers@concordium.com>"]
edition = "2018"
license = "Apache-2.0"
license-file = "../LICENSE-APACHE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wast = "30"
clap = "2.33"
structopt = "0.3"
anyhow = "1.0.33"
ansi_term = "0.12"

[dependencies.wasm-transform]
path = "../wasm-transform"